# Change these first
owner: RJVCA # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Rejuvica Shopify
    url: https://www.rejuvica.com/
  - name: Dermaced Shopify
    url: https://dermaced.com/
  - name: Active Adrenal
    url: https://activeadrenal.com/
  - name: Go Active Ashwagandha
    url: https://goactiveashwagandha.com/
  - name: Redness Redux
    url: https://rednessredux.com/
  - name: Bladder Pro
    url: https://bladderpro.com/
  - name: BloatX
    url: https://bloatx.com/
  - name: Metaven
    url: https://metaven.com/
  - name: Zenapin-IR
    url: https://zenapinir.com/
  - name: Deep Therapy Cream
    url: https://deeptherapycream.com/
  - name: DigestaPro
    url: https://digestapro.com/
  - name: Ancient Pet Liver
    url: https://ancientpetliver.com/
  - name: Activated Female
    url: https://activatedfemale.com/
  - name: Cleanse Drops
    url: https://cleansedrops.com/
  - name: Go Active Ginseng
    url: https://goactiveginseng.com/
  - name: HSN System
    url: https://hsnsystem.com/
  - name: CardioVance
    url: https://cardiovance.com/
  - name: MunoMax
    url: https://munomax.com/
  - name: IntestiClear
    url: https://intesticlear.com/
  - name: Active Iodine
    url: https://activeiodine.com/
  - name: Active Kava Kava
    url: https://activekavakava.com/
  - name: Cleanse Drops Kidney
    url: http://cleansedropskidney.com/
  - name: VitaLiver
    url: https://vitaliver.com/
  - name: Bright Lungs
    url: https://brightlungs.com/
  - name: Go Active Maca
    url: https://goactivemaca.com/
  - name: Activated Male
    url: http://activatedmale.com/
  - name: Nerve Factor
    url: https://nervefactor.com/
  - name: Natal Nourish
    url: https://natalnourish.com/
  - name: Total Soothe
    url: https://totalsoothe.com/
  - name: Ocutonic
    url: https://ocutonic.com/
  - name: Active Olive Leaf
    url: https://activeoliveleaf.com/
  # - name: OraSpark
  #   url: https://oraspark.com/
  - name: Active Polygala
    url: https://activepolygala.com/
  - name: Active Rhodiola
    url: https://activerhodiola.com/
  - name: Better Scalp
    url: https://betterscalp.com/
  - name: Restavin
    url: https://restavin.com/
  - name: NoctuRest
    url: https://nocturest.com/
  - name: Nervestra
    url: https://nervestra.com/
  - name: Prostavec
    url: https://prostavec.com/
  - name: Thyrobin
    url: https://thyrobin.com/
  - name: Uricel
    url: https://uricel.com/
  - name: Balanced Femme
    url: https://balancedfemme.com/
  - name: Cherry Force
    url: https://cherryforce.com/
  - name: Better Nail
    url: https://betternail.com/
  - name: Active Turmeric
    url: https://activeturmeric.com/
  - name: Varicol
    url: https://varicol.com/
  - name: Hydrocin
    url: https://hydrocin.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: uptime.rejuvicahealth.com
  # baseUrl: /your-repo-name
  logoUrl: https://rejuvicahealth.com/rejuvica-uptime-w.svg
  name: Website Monitoring
  favicon: https://rejuvicahealth.com/leaf-uptime.png
  faviconSvg: https://rejuvicahealth.com/leaf-uptime.svg
  # introTitle: "Monitoring all **Rejuvica** sites."
  # introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  #navbar:
   # - title: Status
   #   href: /
   # - title: GitHub
   #   href: https://github.com/$OWNER/$REPO
 
i18n:
 footer: Rejuvica Health

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
